# https://docs.github.com/en/actions/tutorials/create-actions/create-a-composite-action
name: 'Docker action'
inputs:
    cloudsmith_repo:
        required: false
        default: ''
    cloudsmith_token:
        required: false
        default: ''
    workspace_github_repo:
        required: false
        default: ${{ github.repository }}
    workspace_version:
        required: false
        default: ${{ github.sha }}
    package_version:
        required: false
        default: ''
    package_github_repo:
        required: false
        default: ''
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v5
          with:
            ref: ${{ inputs.workspace_version }}
            repository: ${{ inputs.workspace_github_repo }}
        - if: ${{ inputs.package_github_repo != '' }}
          run: |
            cd /ccws
            export WORKSPACE_SRC=${GITHUB_WORKSPACE}
            make set_repo_version REPO=${{ github.server_url }}/${{ inputs.package_github_repo }}.git VERSION=${{ inputs.package_version }}
          shell: bash
        - run: |
            cd /ccws
            export WORKSPACE_SRC=${GITHUB_WORKSPACE}
            make wsupdate_pkgs_shallow
            apt update
            make dep_install
            # VENDOR=sharf VERSION=all are specified in workspace config (.ccws/config.mk)
            make build_all BUILD_PROFILE=deb,reldebug
          env:
            EMAIL: example@example.com
            AUTHOR: CI
            CLOUDSMITH_API_KEY: ${{ inputs.cloudsmith_token }}
          shell: bash
        - run: |
            find ${WORKSPACE_DIR}/artifacts/ -iname *.deb
          shell: bash
        - if: ${{ inputs.cloudsmith_repo != '' }}
          run: |
            python3 -m pip install --break-system-packages cloudsmith-cli
            find ${WORKSPACE_DIR}/artifacts/ -iname *.deb | xargs --no-run-if-empty -I {} cloudsmith push deb ${{ inputs.cloudsmith_repo }} {}
          shell: bash
