var searchData=
[
  ['v_0',['v',['../classvalue__cls.html#ae827beb9a6564e35fc467ef1e0dc28c8',1,'value_cls']]],
  ['va_5flist_1',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray_2',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std::valarray'],['http://en.cppreference.com/w/cpp/header/valarray.html',1,'(Global Namespace)']]],
  ['valid_3',['valid',['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()'],['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()']]],
  ['value_4',['value',['../dinit-util_8h.html#afc6b36559b63cbd85f5f5d2925a819c3',1,'value():&#160;dinit-util.h'],['../structlinked__uo__set_1_1linked__record.html#a211b64470b98d79fc74e69662ccd37fd',1,'linked_uo_set::linked_record::value'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/utility/optional/value.html',1,'std::optional::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()']]],
  ['value_5fcls_5',['value_cls',['../classvalue__cls.html',1,'value_cls&lt; T &gt;'],['../classvalue__cls.html#a6e3a891f16348712f7b189e6cac49777',1,'value_cls::value_cls()']]],
  ['value_5fcomp_6',['value_comp',['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::pmr::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::pmr::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::pmr::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::pmr::set::value_comp()']]],
  ['value_5fcompare_7',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap::value_compare'],['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::pmr::map::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::pmr::multimap::value_compare']]],
  ['value_5for_8',['value_or',['http://en.cppreference.com/w/cpp/utility/optional/value_or.html',1,'std::optional::value_or()'],['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional::value_or()']]],
  ['value_5ftype_9',['value_type',['../classlinked__uo__set_1_1iterator.html#ae4ad1a85c7481a618b969d3aa5e41035',1,'linked_uo_set::iterator::value_type'],['../classlinked__uo__set.html#afc049742d34f1b63843501ca41d20def',1,'linked_uo_set::value_type'],['../classdinit__unordered__set_1_1iterator.html#ad01abf4b40e3bff853ec95a55f920a30',1,'dinit_unordered_set::iterator::value_type'],['../classdinit__unordered__set.html#a3736445dc3b69cd03acf5ac6fba459cb',1,'dinit_unordered_set::value_type']]],
  ['value_5fvar_5fsubst_10',['value_var_subst',['../namespacedinit__load.html#acc472f07b07dbb77b3e9012840135477',1,'dinit_load::value_var_subst(const char *setting_name, std::string &amp;line, std::list&lt; std::pair&lt; unsigned, unsigned &gt; &gt; &amp;offsets, const environment::env_map &amp;envmap, const char *argval)'],['../namespacedinit__load.html#a269b3926dd1c22e6e3f052c75283c169',1,'dinit_load::value_var_subst(const char *setting_name, std::string &amp;line, std::list&lt; std::pair&lt; unsigned, unsigned &gt; &gt; &amp;offsets, const T &amp;var_resolve, const char *argval)']]],
  ['valueless_5fby_5fexception_11',['valueless_by_exception',['http://en.cppreference.com/w/cpp/utility/variant/valueless_by_exception.html',1,'std::variant']]],
  ['var_5fmap_12',['var_map',['../structenvironment_1_1env__map.html#a7f111c00da48a79b3ff3b8904f58ebd4',1,'environment::env_map']]],
  ['variant_13',['variant',['http://en.cppreference.com/w/cpp/header/variant.html',1,'(Global Namespace)'],['http://en.cppreference.com/w/cpp/utility/variant.html',1,'std::variant'],['http://en.cppreference.com/w/cpp/utility/variant/variant.html',1,'std::variant::variant()']]],
  ['variant_5falternative_14',['variant_alternative',['http://en.cppreference.com/w/cpp/utility/variant/variant_alternative.html',1,'std']]],
  ['variant_5falternative_5ft_15',['variant_alternative_t',['http://en.cppreference.com/w/cpp/utility/variant/variant_alternative.html',1,'std']]],
  ['variant_5fsize_16',['variant_size',['http://en.cppreference.com/w/cpp/utility/variant/variant_size.html',1,'std']]],
  ['variant_5fsize_5fv_17',['variant_size_v',['http://en.cppreference.com/w/cpp/utility/variant/variant_size.html',1,'std']]],
  ['vars_18',['vars',['../mconfig-gen_8cc.html#a6aca660546477dccc79054837a0610ee',1,'mconfig-gen.cc']]],
  ['vector_19',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std::pmr::vector'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::pmr::vector::vector()'],['../classcontrol__conn__t.html#a7097486f5ad40ee026abce36143d8365',1,'control_conn_t::vector'],['http://en.cppreference.com/w/cpp/header/vector.html',1,'(Global Namespace)'],['http://en.cppreference.com/w/cpp/container/vector.html',1,'std::vector']]],
  ['vector_3c_20char_2c_20default_5finit_5fallocator_3c_20char_20_3e_20_3e_20',['vector&lt; char, default_init_allocator&lt; char &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20const_20char_20_2a_20_3e_21',['vector&lt; const char * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20dir_5fentry_20_3e_22',['vector&lt; dir_entry &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20service_5frlimits_20_3e_23',['vector&lt; service_rlimits &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3alist_3c_20k_20_3e_20_3e_24',['vector&lt; std::list&lt; K &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3alist_3c_20linked_5fuo_5fset_3a_3alinked_5frecord_20_3e_20_3e_25',['vector&lt; std::list&lt; linked_uo_set::linked_record &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3alist_3c_20std_3a_3astring_20_3e_20_3e_26',['vector&lt; std::list&lt; std::string &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20void_20_2a_20_3e_27',['vector&lt; void * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['version_28',['version',['http://en.cppreference.com/w/cpp/header/version.html',1,'']]],
  ['vfprintf_29',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf_30',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf_31',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf_32',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['visit_33',['visit',['http://en.cppreference.com/w/cpp/utility/variant/visit.html',1,'std']]],
  ['visited_34',['visited',['../classservice__record.html#afb8c1a2a11b7d6f7a057d586bd5b6c6e',1,'service_record']]],
  ['void_5ft_35',['void_t',['http://en.cppreference.com/w/cpp/types/void_t.html',1,'std']]],
  ['vprintf_36',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf_37',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf_38',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf_39',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf_40',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf_41',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf_42',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf_43',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf_44',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
