var searchData=
[
  ['scoped_5fallocator_5fadaptor_0',['scoped_allocator_adaptor',['http://en.cppreference.com/w/cpp/memory/scoped_allocator_adaptor.html',1,'std']]],
  ['scripted_5fservice_1',['scripted_service',['../classscripted__service.html',1,'']]],
  ['seconds_2',['seconds',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['seed_5fseq_3',['seed_seq',['http://en.cppreference.com/w/cpp/numeric/random/seed_seq.html',1,'std']]],
  ['select_5fevents_4',['select_events',['../classdasynq_1_1select__events.html',1,'dasynq']]],
  ['select_5ftraits_5',['select_traits',['../classdasynq_1_1select__traits.html',1,'dasynq']]],
  ['sentry_6',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wstringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::osyncstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::strstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wfstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wiostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wosyncstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_osyncstream::sentry']]],
  ['septnode_7',['septnode',['../structdasynq_1_1btree__set_1_1septnode.html',1,'dasynq::btree_set']]],
  ['sequence_8',['sequence',['../classcts_1_1sequence.html',1,'cts']]],
  ['sequenced_5fpolicy_9',['sequenced_policy',['http://en.cppreference.com/w/cpp/algorithm/execution_policy_tag_t.html',1,'std::execution']]],
  ['service_5fchild_5fwatcher_10',['service_child_watcher',['../classservice__child__watcher.html',1,'']]],
  ['service_5fcyclic_5fdependency_11',['service_cyclic_dependency',['../classservice__cyclic__dependency.html',1,'']]],
  ['service_5fdep_12',['service_dep',['../classservice__dep.html',1,'']]],
  ['service_5fdescription_5fexc_13',['service_description_exc',['../classservice__description__exc.html',1,'']]],
  ['service_5fdir_5fopt_14',['service_dir_opt',['../classservice__dir__opt.html',1,'']]],
  ['service_5fflags_5ft_15',['service_flags_t',['../structservice__flags__t.html',1,'']]],
  ['service_5flistener_16',['service_listener',['../classservice__listener.html',1,'']]],
  ['service_5fload_5ferror_17',['service_load_error',['../classservice__load__error.html',1,'']]],
  ['service_5fload_5fexc_18',['service_load_exc',['../classservice__load__exc.html',1,'']]],
  ['service_5fnot_5ffound_19',['service_not_found',['../classservice__not__found.html',1,'']]],
  ['service_5fop_5fcancel_20',['service_op_cancel',['../classservice__op__cancel.html',1,'']]],
  ['service_5frecord_21',['service_record',['../classservice__record.html',1,'']]],
  ['service_5frlimits_22',['service_rlimits',['../structservice__rlimits.html',1,'']]],
  ['service_5fset_23',['service_set',['../classservice__set.html',1,'']]],
  ['service_5fsettings_5fwrapper_24',['service_settings_wrapper',['../classdinit__load_1_1service__settings__wrapper.html',1,'dinit_load']]],
  ['set_25',['set',['http://en.cppreference.com/w/cpp/container/set.html',1,'std::pmr::set'],['http://en.cppreference.com/w/cpp/container/set.html',1,'std::set']]],
  ['setting_5fdetails_26',['setting_details',['../structdinit__load_1_1setting__details.html',1,'dinit_load']]],
  ['shared_5ffuture_27',['shared_future',['http://en.cppreference.com/w/cpp/thread/shared_future.html',1,'std']]],
  ['shared_5flock_28',['shared_lock',['http://en.cppreference.com/w/cpp/thread/shared_lock.html',1,'std']]],
  ['shared_5fmutex_29',['shared_mutex',['http://en.cppreference.com/w/cpp/thread/shared_mutex.html',1,'std']]],
  ['shared_5fptr_30',['shared_ptr',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5ftimed_5fmutex_31',['shared_timed_mutex',['http://en.cppreference.com/w/cpp/thread/shared_timed_mutex.html',1,'std']]],
  ['shuffle_5forder_5fengine_32',['shuffle_order_engine',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine.html',1,'std']]],
  ['sig_5fatomic_5ft_33',['sig_atomic_t',['http://en.cppreference.com/w/cpp/utility/program/sig_atomic_t.html',1,'std']]],
  ['sig_5fcapture_5ftempl_34',['sig_capture_templ',['../classdasynq_1_1dprivate_1_1dkqueue_1_1sig__capture__templ.html',1,'dasynq::sig_capture_templ&lt; T &gt;'],['../classdasynq_1_1dprivate_1_1signal__mech_1_1sig__capture__templ.html',1,'dasynq::sig_capture_templ&lt; T &gt;']]],
  ['sigdata_5ft_35',['sigdata_t',['../classdasynq_1_1signal__traits_1_1sigdata__t.html',1,'dasynq::signal_traits::sigdata_t'],['../classdasynq_1_1v2_1_1epoll__traits_1_1sigdata__t.html',1,'dasynq::v2::epoll_traits::sigdata_t'],['../classdasynq_1_1v2_1_1kqueue__traits_1_1sigdata__t.html',1,'dasynq::v2::kqueue_traits::sigdata_t']]],
  ['signal_5fevents_36',['signal_events',['../classdasynq_1_1signal__events.html',1,'dasynq']]],
  ['signal_5fevents_3c_20base_2c_20false_20_3e_37',['signal_events&lt; Base, false &gt;',['../classdasynq_1_1signal__events.html',1,'dasynq']]],
  ['signal_5fevents_3c_20base_2c_20true_20_3e_38',['signal_events&lt; Base, true &gt;',['../classdasynq_1_1signal__events.html',1,'dasynq']]],
  ['signal_5fname_5fnumber_5fpair_39',['signal_name_number_pair',['../structdinit__load_1_1signal__name__number__pair.html',1,'dinit_load']]],
  ['signal_5ftraits_40',['signal_traits',['../classdasynq_1_1signal__traits.html',1,'dasynq']]],
  ['signal_5fwatcher_41',['signal_watcher',['../classdasynq_1_1v2_1_1dprivate_1_1signal__watcher.html',1,'dasynq::v2::dprivate']]],
  ['signal_5fwatcher_5fimpl_42',['signal_watcher_impl',['../classdasynq_1_1v2_1_1dprivate_1_1signal__watcher__impl.html',1,'dasynq::v2::dprivate']]],
  ['size_5ft_43',['size_t',['http://en.cppreference.com/w/cpp/types/size_t.html',1,'std']]],
  ['slice_44',['slice',['http://en.cppreference.com/w/cpp/numeric/valarray/slice.html',1,'std']]],
  ['slice_5farray_45',['slice_array',['http://en.cppreference.com/w/cpp/numeric/valarray/slice_array.html',1,'std']]],
  ['slist_46',['slist',['../classslist.html',1,'']]],
  ['slist_3c_20service_5frecord_2c_20extract_5fprop_5fqueue_20_3e_47',['slist&lt; service_record, extract_prop_queue &gt;',['../classslist.html',1,'']]],
  ['slist_3c_20service_5frecord_2c_20extract_5fstop_5fqueue_20_3e_48',['slist&lt; service_record, extract_stop_queue &gt;',['../classslist.html',1,'']]],
  ['smatch_49',['smatch',['http://en.cppreference.com/w/cpp/regex/match_results.html',1,'std']]],
  ['source_5flocation_50',['source_location',['http://en.cppreference.com/w/cpp/experimental/source_location.html',1,'std::experimental']]],
  ['space_5finfo_51',['space_info',['http://en.cppreference.com/w/cpp/experimental/fs/space_info.html',1,'std::experimental::filesystem::space_info'],['http://en.cppreference.com/w/cpp/filesystem/space_info.html',1,'std::filesystem::space_info']]],
  ['span_52',['span',['http://en.cppreference.com/w/cpp/container/span.html',1,'std']]],
  ['sregex_5fiterator_53',['sregex_iterator',['http://en.cppreference.com/w/cpp/regex/regex_iterator.html',1,'std']]],
  ['sregex_5ftoken_5fiterator_54',['sregex_token_iterator',['http://en.cppreference.com/w/cpp/regex/regex_token_iterator.html',1,'std']]],
  ['ssub_5fmatch_55',['ssub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['stable_5fheap_56',['stable_heap',['../classdasynq_1_1stable__heap.html',1,'dasynq']]],
  ['stable_5fheap_3c_20node_5ftype_2c_20int_20_3e_57',['stable_heap&lt; node_type, int &gt;',['../classdasynq_1_1stable__heap.html',1,'dasynq']]],
  ['stable_5fprio_58',['stable_prio',['../classdasynq_1_1stable__prio.html',1,'dasynq']]],
  ['stack_59',['stack',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['stack_3c_20file_5finput_5fstack_3a_3ainput_5ffile_20_3e_60',['stack&lt; file_input_stack::input_file &gt;',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['state_5ftype_61',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_byname::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf16::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8_utf16::state_type']]],
  ['static_5flength_5ft_62',['static_length_t',['../structcts_1_1static__length__t.html',1,'cts']]],
  ['static_5flength_5ft_3c_20char_5bn_5d_3e_63',['static_length_t&lt; char[N]&gt;',['../structcts_1_1static__length__t_3_01char_0fN_0e_4.html',1,'cts']]],
  ['static_5fmembuf_64',['static_membuf',['../classstatic__membuf.html',1,'']]],
  ['static_5fstring_65',['static_string',['../classcts_1_1static__string.html',1,'cts']]],
  ['steady_5fclock_66',['steady_clock',['http://en.cppreference.com/w/cpp/chrono/steady_clock.html',1,'std::chrono']]],
  ['stop_5fchild_5fwatcher_67',['stop_child_watcher',['../classstop__child__watcher.html',1,'']]],
  ['stop_5fstatus_5fpipe_5fwatcher_68',['stop_status_pipe_watcher',['../classstop__status__pipe__watcher.html',1,'']]],
  ['streambuf_69',['streambuf',['http://en.cppreference.com/w/cpp/io/basic_streambuf.html',1,'std']]],
  ['streamoff_70',['streamoff',['http://en.cppreference.com/w/cpp/io/streamoff.html',1,'std']]],
  ['streampos_71',['streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['streamsize_72',['streamsize',['http://en.cppreference.com/w/cpp/io/streamsize.html',1,'std']]],
  ['string_73',['string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::string'],['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::pmr::string']]],
  ['string_5ftype_74',['string_type',['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/money_put.html',1,'std::money_put::string_type'],['http://en.cppreference.com/w/cpp/locale/money_get.html',1,'std::money_get::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate::string_type']]],
  ['string_5fview_75',['string_view',['http://en.cppreference.com/w/cpp/experimental/basic_string_view.html',1,'std::experimental::string_view'],['http://en.cppreference.com/w/cpp/string/basic_string_view.html',1,'std::string_view'],['../classstring__view.html',1,'string_view']]],
  ['stringbuf_76',['stringbuf',['http://en.cppreference.com/w/cpp/io/basic_stringbuf.html',1,'std']]],
  ['stringstream_77',['stringstream',['http://en.cppreference.com/w/cpp/io/basic_stringstream.html',1,'std']]],
  ['stringview_78',['stringview',['../structstringview.html',1,'']]],
  ['strong_5fequality_79',['strong_equality',['http://en.cppreference.com/w/cpp/utility/compare/strong_equality.html',1,'std']]],
  ['strong_5fordering_80',['strong_ordering',['http://en.cppreference.com/w/cpp/utility/compare/strong_ordering.html',1,'std']]],
  ['strstream_81',['strstream',['http://en.cppreference.com/w/cpp/io/strstream.html',1,'std']]],
  ['strstreambuf_82',['strstreambuf',['http://en.cppreference.com/w/cpp/io/strstreambuf.html',1,'std']]],
  ['student_5ft_5fdistribution_83',['student_t_distribution',['http://en.cppreference.com/w/cpp/numeric/random/student_t_distribution.html',1,'std']]],
  ['sub_5fmatch_84',['sub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['subproc_5fbuffer_85',['subproc_buffer',['../classsubproc__buffer.html',1,'']]],
  ['subproc_5fout_5fwatch_86',['subproc_out_watch',['../classsubproc__out__watch.html',1,'']]],
  ['subtract_5fwith_5fcarry_5fengine_87',['subtract_with_carry_engine',['http://en.cppreference.com/w/cpp/numeric/random/subtract_with_carry_engine.html',1,'std']]],
  ['svector_88',['svector',['../classdasynq_1_1svector.html',1,'dasynq']]],
  ['svector_3c_20dasynq_3a_3adary_5fheap_3a_3aheap_5fnode_20_3e_89',['svector&lt; dasynq::dary_heap::heap_node &gt;',['../classdasynq_1_1svector.html',1,'dasynq']]],
  ['syncbuf_90',['syncbuf',['http://en.cppreference.com/w/cpp/io/basic_syncbuf.html',1,'std']]],
  ['synchronized_5fpool_5fresource_91',['synchronized_pool_resource',['http://en.cppreference.com/w/cpp/experimental/synchronized_pool_resource.html',1,'std::experimental::pmr::synchronized_pool_resource'],['http://en.cppreference.com/w/cpp/memory/synchronized_pool_resource.html',1,'std::pmr::synchronized_pool_resource']]],
  ['system_5fclock_92',['system_clock',['http://en.cppreference.com/w/cpp/chrono/system_clock.html',1,'std::chrono']]],
  ['system_5ferror_93',['system_error',['http://en.cppreference.com/w/cpp/error/system_error.html',1,'std']]]
];
