on:
    push:
        branches:
            - '**'
        tags:
            - 'NEVER'
    pull_request:
        types: [opened, reopened]

jobs:
    tests:
        uses: asherikov/ccws/.github/workflows/reusable_test.yaml@master
        with:
            distro: noble
            workspace_github_repo: asherikov/sharf
            workspace_version: ${{ github.sha }}
