on: [push, pull_request]

jobs:
    ubuntu_latest_static:
        runs-on: ubuntu-latest
        env:
            BUILD_PROFILE: static_checks
        steps:
            - uses: actions/checkout@v4
              with:
                  repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                  ref: main
                  path: src
            - run: make bp_install_build
            - run: make wsupdate_pkgs_shallow
            - run: rm -rf src/ariles/ariles2_rosparam_ws
            - run: make

    ubuntu_latest_tidy:
        runs-on: ubuntu-latest
        env:
            BUILD_PROFILE: scan_build
        steps:
            - uses: actions/checkout@v4
              with:
                  repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                  ref: main
                  path: src
            - run: make bp_install_build
            - run: make wsupdate_pkgs_shallow
            - run: make dep_install
            - run: rm -rf src/ariles/ariles2_rosparam_ws
            - run: make build_all

    ubuntu_latest_reldebug:
        runs-on: ubuntu-latest
        env:
            BUILD_PROFILE: reldebug
        steps:
            - uses: actions/checkout@v4
              with:
                  repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                  ref: main
                  path: src
            - run: make bp_install_build
            - run: make wsupdate_pkgs_shallow
            - run: make dep_install
            - run: rm -rf src/ariles/ariles2_rosparam_ws
            - run: make build_all
            - run: make wstest

    ubuntu_latest_addr_sanitizer:
        runs-on: ubuntu-latest
        env:
            BUILD_PROFILE: addr_undef_sanitizers
        steps:
            - uses: actions/checkout@v4
              with:
                  repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                  ref: main
                  path: src
            - run: make bp_install_build
            - run: make wsupdate_pkgs_shallow
            - run: make dep_install
            - run: rm -rf src/ariles/ariles2_rosparam_ws
            - run: make build_all
            - run: make wstest

    ubuntu_latest_thread_sanitizer:
        runs-on: ubuntu-latest
        env:
            BUILD_PROFILE: thread_sanitizer
        steps:
            - uses: actions/checkout@v4
              with:
                  repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                  ref: main
                  path: src
            - run: make bp_install_build
            - run: make wsupdate_pkgs_shallow
            - run: make dep_install
            - run: rm -rf src/ariles/ariles2_rosparam_ws
            - run: echo "race:libfastrtps.so.*" >> ccws/profiles/build/thread_sanitizer/thread.supp
            - run: make build_all
            - run: make wstest

    ubuntu_latest_doxygen:
        runs-on: ubuntu-latest
        env:
            BUILD_PROFILE: doxygen
        steps:
            - uses: actions/checkout@v4
              with:
                  repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                  ref: main
                  path: src
            - run: make bp_install_build
            - run: make wsupdate_pkgs_shallow
            - run: make dep_install
            - run: rm -rf src/ariles/ariles2_rosparam_ws
            - run: make

    ubuntu_latest_deb:
        runs-on: ubuntu-latest
        env:
            EMAIL: example@example.com
            AUTHOR: CI
        steps:
            - uses: actions/checkout@v4
              with:
                  repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                  ref: main
                  path: src
            - run: make bp_install_build BUILD_PROFILE=reldebug
            - run: make bp_install_build BUILD_PROFILE=deb
            - run: make wsupdate_pkgs_shallow
            - run: make dep_install
            - run: rm -rf src/ariles/ariles2_rosparam_ws
            - run: make build_all BUILD_PROFILE=deb BASE_BUILD_PROFILE=reldebug VENDOR=sharf
