on:
    push:
        branches:
            - '**'
        tags:
            - 'NEVER'
    pull_request:
        types: [opened, reopened]

jobs:
    gh_pages:
        uses: asherikov/ccws/.github/workflows/reusable_dox.yaml@master
        with:
            distro: noble
            version: ${{ github.ref_name }}
            push: true
        permissions:
            contents: write
