on:
    push:
        tags:
            - '**'

jobs:
    gh_pages:
        uses: asherikov/ccws/.github/workflows/reusable_dox.yaml@master
        with:
            distro: noble
            version: ${{ github.ref_name }}
#            push: false
        permissions:
            contents: write

    deb_jammy:
        uses: asherikov/ccws/.github/workflows/reusable_deb.yaml@master
        with:
            distro: jammy
            workspace_github_repo: asherikov/sharf
            workspace_version: ${{ github.sha }}
            cloudsmith_repo: asherikov-aV7/all/ubuntu/jammy
            build_target: "PKG='ariles2_graphviz_ws ariles2_namevalue2_ws ariles2_octave_ws ariles2_pugixml_ws ariles2_ros2param_ws ariles2_yamlcpp_ws cdinit_ros2 graphite_to_mcap intrometry_frontend intrometry_pjmsg_mcap intrometry_pjmsg_topic intrometry_tests pjmsg_mcap_wrapper'"
        secrets:
            cloudsmith_token: ${{ secrets.CLOUDSMITH_API_KEY }}

    deb_noble:
        uses: asherikov/ccws/.github/workflows/reusable_deb.yaml@master
        with:
            distro: noble
            workspace_github_repo: asherikov/sharf
            workspace_version: ${{ github.sha }}
            cloudsmith_repo: asherikov-aV7/all/ubuntu/noble
            build_target: "PKG='ariles2_graphviz_ws ariles2_namevalue2_ws ariles2_octave_ws ariles2_pugixml_ws ariles2_ros2param_ws ariles2_yamlcpp_ws cdinit_ros2 graphite_to_mcap intrometry_frontend intrometry_pjmsg_mcap intrometry_pjmsg_topic intrometry_tests pjmsg_mcap_wrapper'"
        secrets:
            cloudsmith_token: ${{ secrets.CLOUDSMITH_API_KEY }}

    deb_noble_arm64:
        uses: asherikov/ccws/.github/workflows/reusable_deb.yaml@master
        with:
            distro: noble
            workspace_github_repo: asherikov/sharf
            workspace_version: ${{ github.sha }}
            cloudsmith_repo: asherikov-aV7/all/ubuntu/noble
            profile: cross_arm64
            build_target: "PKG='ariles2_graphviz_ws ariles2_namevalue2_ws ariles2_octave_ws ariles2_pugixml_ws ariles2_ros2param_ws ariles2_yamlcpp_ws cdinit_ros2 graphite_to_mcap intrometry_frontend intrometry_pjmsg_mcap intrometry_pjmsg_topic intrometry_tests pjmsg_mcap_wrapper'"
        secrets:
            cloudsmith_token: ${{ secrets.CLOUDSMITH_API_KEY }}
